# Generated by Django 4.2.6 on 2023-10-18 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                ("address", models.CharField(max_length=340)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo_name", models.CharField(max_length=40)),
                ("cargo_quantity", models.PositiveIntegerField()),
                ("cargo_quantity_allowance", models.PositiveIntegerField()),
                ("load_port", models.CharField(max_length=40)),
                ("discharge_port", models.CharField(max_length=40)),
                ("date_open", models.DateField()),
                ("date_close", models.DateField()),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="booking_manager_app.account",
                    ),
                ),
            ],
        ),
    ]
