# Generated by Django 4.2.6 on 2023-10-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ships_manager_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ship",
            name="year_of_built",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="speed",
            name="consumption_additional",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="speed",
            name="consumption_main",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="speed",
            name="ship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ships_manager_app.ship",
            ),
        ),
        migrations.AddField(
            model_name="speed",
            name="speed_in_kn",
            field=models.FloatField(default=0),
        ),
    ]
