# Generated by Django 4.2.6 on 2023-10-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ships_manager_app",
            "0002_ship_year_of_built_speed_consumption_additional_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="speed",
            name="load_status",
            field=models.CharField(
                choices=[("ballast", "Ballast"), ("laden", "Laden")],
                default="ballast",
                max_length=10,
            ),
        ),
    ]
