# Generated by Django 4.2.6 on 2023-10-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ships_manager_app", "0004_alter_ship_year_of_built_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speed",
            name="load_status",
            field=models.CharField(
                choices=[("ballast", "Ballast"), ("laden", "Laden")],
                max_length=10,
            ),
        ),
    ]
