# Generated by Django 4.2.6 on 2023-10-18 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ships_manager_app", "0006_alter_speed_consumption_additional_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speed",
            name="consumption_additional",
            field=models.FloatField(
                blank=True,
                default=0,
                validators=[django.core.validators.MaxValueValidator(20.0)],
            ),
        ),
    ]
