# Generated by Django 4.2.6 on 2023-10-18 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ships_manager_app",
            "0008_alter_speed_consumption_additional_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ship",
            name="year_of_built",
            field=models.PositiveIntegerField(
                blank=True,
                default=2000,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900.0),
                    django.core.validators.MaxValueValidator(3000.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="speed",
            name="consumption_additional",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="speed",
            name="consumption_main",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="speed",
            name="speed_in_kn",
            field=models.FloatField(default=0),
        ),
    ]
